version: '3'
services:

  app:
    image: safe4us.azurecr.io/safe4us:v1
    container_name: safe4us
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    depends_on: 
      - solr
      - redis
    environment:
      SAFETYFORM_ENVIRONMENT: development
    working_dir: /var/www
    networks:
      - safe4us-network

  solr:
    image: safe4us.azurecr.io/solr:v1
    container_name: solr
    ports:
      - "8983:8983"
    entrypoint:
      - sh
      - "-c"
      - "precreate-core safetyform_asset /opt/solr/server/solr/configsets/asset; precreate-core safetyform_building /opt/solr/server/solr/configsets/building; precreate-core safetyform_floor /opt/solr/server/solr/configsets/floor; precreate-core safetyform_space /opt/solr/server/solr/configsets/space; precreate-core safetyform_permit /opt/solr/server/solr/configsets/permit;  exec solr -f"
    networks:
      - safe4us-network

  redis:
      image: library/redis:latest
      container_name: redis
      networks:
        - safe4us-network

networks:
  safe4us-network:
    driver: bridge
